### ISSUE TITLE
Empty Migrations version file

### ISSUE THREAD

**Issue by edger-asiimwe** [MQ-xz/multi-tenancy-in-flask#1]
Hey, 

Thanks for this comprehensive blueprint and the accompanying Medium article. I followed the article but can't seem to have a valid tenant migration version file. 

Inside the **upgrade** and **downgrade** method, it is blank. Is this normal?

The database gets populated with the tables, but was worried might have issues if I run the upgrade on the production server.

![image](https://github.com/MQ-xz/multi-tenancy-in-flask/assets/25789529/bc0d880e-023c-4b6e-9493-9479bba75f59)

Could you please provide the procedure to follow? A step-by-step guide on the workflow, from the public to tenant migrations.

Thanks

**Comment by MQ-xz** [comment]
If you defined any tenant-related models, there should be a migration file for those models in the tenant migrations folder. Please verify that the following parts are properly which is addressed in the blog:

1. Initialize Tenant Schema
2. Customize Migration Script 
3. Initial Migration for Tenant Schema

Also, check the commit history mentioned in the blog for more reference. If you still have issues, please share code snippets for these parts so I can review them.

**Comment by edger-asiimwe** [comment]
I have tenant-related models defined already, and a migration script for them - which I customized based on the blog. Issue comes in when creating the migration script for the tenant. It creates the migration script with an empty version folder - which I believe should contain the migrations to run on the **upgrade** command. The schema and tables for each tenant are created as well in the database, even though the migrations versions folder is empty. 

In the blog, the **public models** are enhanced with the **__bind_key__** and **__table_args__** after initializing the migrations for the public models, but before running the **flask db migrate -d migrations/public/**

For the tenant models, should the order be.

1. Define the models 
2. Run `flask db init -d migrations/tenant/`
3. Create the initial schema via the psql shell
4. Run `flask db migrate -d migrations/tenant/`
5. Then `flask db upgrade -d migrations/tenant/`

Also in the blog (Initial Migration for Tenant Schema), you highlight the need to create a schema first manually with the psql shell, and then add it to the tenant list. How would you achieve this?

**Comment by edger-asiimwe** [comment]
![image](https://github.com/MQ-xz/multi-tenancy-in-flask/assets/25789529/d0095040-1ede-4b7f-b2f1-eee43a0595cc)

From this, we can see that a migration is created but has empty **upgrade** and **downgrade** methods content. 

![image](https://github.com/MQ-xz/multi-tenancy-in-flask/assets/25789529/7374ef0c-9295-4bb6-8b42-3da9d86f3d11)

This is a snapshot of the tables created when a tenant is created using the register endpoint. The initial schema created using the psql shell does not have the tables in it.

**Comment by MQ-xz** [comment]
To achieve Initial Migration for Tenant Scheme, create a schema manually via psql shell and add that schema name in the tenants list in the file [migrations/tenant/env.py](https://github.com/MQ-xz/multi-tenancy-in-flask/blob/3de786e00abf283e7d962f4888af359bb77c5d93/migrations/tenant/env.py#L55) manually and run the migration (`flask db migrate -d migrations/tenant/`) 

ref:
1. Check the following commit changes https://github.com/MQ-xz/multi-tenancy-in-flask/commit/6e5aec2da2ecbe645d208ed90ef12a4682670747

**Comment by edger-asiimwe** [comment]
Works perfectly 👊

I don't think I should be worried about the tables not being created inside that temporary intital test schema, right? 

FYI. The new tenant created via the register endpoint has his tables created. 

Thanks.

**Comment by MQ-xz** [comment]
> Works perfectly 👊
> 
> I don't think I should be worried about the tables not being created inside that temporary intital test schema, right? 
> 
> FYI. The new tenant created via the register endpoint has his tables created. 
> 
> Thanks.

There is no issue with that you can run the upgrade command if you need to create the tables in the temporary schema while keeping the schema name in that tenant list.

Also don't forget to revert the tenant list back to the tenant fech query.
